### ISSUE TITLE
size to filesize

### ISSUE THREAD

**Issue by sdembele** [gopalmallya/csv2table#1]
Hi Gapalmallya
Great job, 
But there are somethink that you need to change in remote_url_table.sql file at line 10
***size*** must be ***filesize*** 
Thanks

**Comment by gopalmallya** [comment]
Hi sdembele

Thank you for trying out csv2table plugin and words of appreciation. 

I have fixed the remote_url_table.sql and added  demo application for version 5.1.4 and 20.2 and instructions to install demo app in README.md

Best Regards

Gopal

**Comment by gopalmallya** [comment]
Fixed the script , required to install demo app.
